# PowerControllerViewer example configuration file


Website:
  HostingIP: 127.0.0.1
  Port: 8000
  PageAutoRefresh: 15
  DebugMode: True
  AccessKey: 

Files:
  LogfileName: logfile.log
  LogProcessID: True          # Include the process ID in the log entries
  LogfileMaxLines: 5000       # How much information do we write to the log file. One of: none; error; warning; summary; detailed; debug; all
  LogfileVerbosity: detailed  # How much information do we write to the console. One of: error; warning; summary; detailed; debug; all
  ConsoleVerbosity: summary
  DeleteOldStateFiles: 168      # Delete state files older than this many hours. Set to 0 or blank to disable deletion.

